import { Resend } from "resend";

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

export async function sendTeardownReport({ to, brandName, dateStr, pdfUrl, pdfBuffer }) {
  if (!resend) {
    throw new Error("RESEND_API_KEY not configured");
  }

  if (!to || !to.trim()) {
    throw new Error("Email address required");
  }

  const subject = `${brandName} Website Improvement Report - Ecommerce Teardown ${dateStr}`;
  const fromEmail = process.env.RESEND_FROM_EMAIL || "reports@ecommerceteardown.com";

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            line-height: 1.6;
            color: #1A1A1A;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
          }
          .header {
            text-align: center;
            padding: 20px 0;
            border-bottom: 2px solid #00A651;
            margin-bottom: 30px;
          }
          .header h1 {
            color: #00A651;
            margin: 0;
            font-size: 24px;
          }
          .content {
            margin: 30px 0;
          }
          .button {
            display: inline-block;
            background: #00A651;
            color: white;
            padding: 14px 28px;
            text-decoration: none;
            border-radius: 6px;
            font-weight: 700;
            margin: 20px 0;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 14px;
          }
          .footer a {
            color: #00A651;
            text-decoration: none;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Your Website Improvement Report is Ready</h1>
        </div>
        <div class="content">
          <p>Hi there,</p>
          <p>Your <strong>${brandName} Website Improvement Report</strong> has been generated and is ready to download.</p>
          <p style="text-align: center;">
            <a href="${pdfUrl}" class="button">Download PDF Report</a>
          </p>
          <p>This report includes:</p>
          <ul>
            <li>Mobile and desktop screenshots</li>
            <li>Friction points analysis</li>
            <li>Prioritized fixes (quick wins, medium lifts, experiments)</li>
            <li>Copy suggestions</li>
            <li>Mobile & accessibility notes</li>
          </ul>
          <p>If you have any questions about your report, feel free to reach out.</p>
        </div>
        <div class="footer">
          <p>Generated by <a href="https://ecommerceteardown.com">ecommerceteardown.com</a></p>
          <p>© ${new Date().getFullYear()} Ecommerce Teardown. All rights reserved.</p>
        </div>
      </body>
    </html>
  `;

  try {
    const result = await resend.emails.send({
      from: fromEmail,
      to: to.trim(),
      subject,
      html,
      attachments: pdfBuffer
        ? [
            {
              filename: `${brandName.replace(/\./g, '-')}-Website-Improvement-Report-Ecommerce-Teardown-${dateStr}.pdf`,
              content: Buffer.isBuffer(pdfBuffer) ? pdfBuffer.toString("base64") : pdfBuffer
            }
          ]
        : []
    });

    if (result.error) {
      throw new Error(`Resend API error: ${result.error.message || JSON.stringify(result.error)}`);
    }

    return { success: true, messageId: result.data?.id };
  } catch (error) {
    throw new Error(`Failed to send email: ${error.message || String(error)}`);
  }
}

